apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-rc
spec:
  selector:
    matchLabels:
      env: dev
  replicas: 3
  template:
    metadata:
      name: ide-pod
      labels:
        env: dev
    spec:
      containers:
      - image: nginx
        name: nginx-containers