apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deploy
  labels:
    mon: hyd
spec:
  selector:
    matchLabels:
      env: dev
  replicas: 3
  template:
    metadata:
      name: first-depo
      labels:
        env: dev
    spec:
      containers:
      - image: nginx
        name: nginx-container
