apiVersion: v1
kind: ReplicationController
metadata:
  name: new-rc
spec:
  replicas: 3
  template:
    metadata:
      name: ide-pod
      labels:
        env: dev
    spec:
      containers:
      - image: nginx
        name: nginx-containers